//! Thin FFI bindings for the Verifone C SDK.
//!
//! This is the only module in the crate that uses `unsafe`.  It exists because
//! the vendor SDK is distributed as a C library and Rust has no mechanism to
//! call C functions without `extern "C"` blocks and raw pointers.  All unsafe
//! operations are confined here and wrapped with enough validation that the
//! public [`crate::verifone`] API is safe to call.
//!
//! Invariants maintained by this module:
//! * Function pointers are only dereferenced after the SDK reports success.
//! * Output buffers are fully zero-initialized before being passed to C.
//! * Returned C strings are converted to Rust strings by the safe API layer.
//! * The opaque `VxTerminal` pointer is owned by [`crate::verifone::TerminalHandle`].

#![allow(unsafe_code)]

use crate::verifone::error::VerifoneError;

// The C types below mirror `packages/verifone-ffi/include/verifone.h`.
// In a build that links the real SDK these would be generated by bindgen.

#[repr(C)]
pub struct VxTerminal {
    _private: [u8; 0],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VxCardInfo {
    pub present: u8,
    pub brand: [std::ffi::c_char; 32],
    pub last_four: [std::ffi::c_char; 5],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VxPaymentResult {
    pub result: i32,
    pub auth_code: [std::ffi::c_char; 16],
    pub opaque_token: [std::ffi::c_char; 256],
    pub terminal_id: [std::ffi::c_char; 64],
    pub authorized_amount_cents: u64,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VxRefundResult {
    pub result: i32,
    pub reference: [std::ffi::c_char; 128],
    pub refunded_amount_cents: u64,
}

extern "C" {
    pub fn vx_init_terminal(out_terminal: *mut *mut VxTerminal) -> i32;
    pub fn vx_start_transaction(
        terminal: *mut VxTerminal,
        amount_cents: u64,
        currency: *const std::ffi::c_char,
    ) -> i32;
    pub fn vx_wait_for_card(
        terminal: *mut VxTerminal,
        timeout_ms: u32,
        out_card: *mut VxCardInfo,
    ) -> i32;
    pub fn vx_process_payment(terminal: *mut VxTerminal, out_result: *mut VxPaymentResult) -> i32;
    pub fn vx_refund(
        terminal: *mut VxTerminal,
        transaction_id: *const std::ffi::c_char,
        amount_cents: u64,
        currency: *const std::ffi::c_char,
        out_result: *mut VxRefundResult,
    ) -> i32;
    pub fn vx_close_terminal(terminal: *mut VxTerminal) -> i32;
}

/// Safe wrapper around `vx_init_terminal`.
pub fn init_terminal() -> Result<*mut VxTerminal, VerifoneError> {
    let mut ptr: *mut VxTerminal = std::ptr::null_mut();
    let rc = unsafe { vx_init_terminal(&mut ptr) };
    VerifoneError::from_result(rc)?;
    if ptr.is_null() {
        return Err(VerifoneError::UnexpectedNullHandle);
    }
    Ok(ptr)
}

/// Safe wrapper around `vx_start_transaction`.
pub fn start_transaction(
    ptr: *mut VxTerminal,
    amount_cents: u64,
    currency: &std::ffi::CStr,
) -> Result<(), VerifoneError> {
    let rc = unsafe { vx_start_transaction(ptr, amount_cents, currency.as_ptr()) };
    VerifoneError::from_result(rc)
}

/// Safe wrapper around `vx_wait_for_card`.
pub fn wait_for_card(ptr: *mut VxTerminal, timeout_ms: u32) -> Result<VxCardInfo, VerifoneError> {
    let mut info: VxCardInfo = unsafe { std::mem::zeroed() };
    let rc = unsafe { vx_wait_for_card(ptr, timeout_ms, &mut info) };
    VerifoneError::from_result(rc)?;
    Ok(info)
}

/// Safe wrapper around `vx_process_payment`.
pub fn process_payment(ptr: *mut VxTerminal) -> Result<VxPaymentResult, VerifoneError> {
    let mut result: VxPaymentResult = unsafe { std::mem::zeroed() };
    let rc = unsafe { vx_process_payment(ptr, &mut result) };
    VerifoneError::from_result(rc)?;
    Ok(result)
}

/// Safe wrapper around `vx_refund`.
pub fn refund(
    ptr: *mut VxTerminal,
    transaction_id: &std::ffi::CStr,
    amount_cents: u64,
    currency: &std::ffi::CStr,
) -> Result<VxRefundResult, VerifoneError> {
    let mut result: VxRefundResult = unsafe { std::mem::zeroed() };
    let rc = unsafe {
        vx_refund(
            ptr,
            transaction_id.as_ptr(),
            amount_cents,
            currency.as_ptr(),
            &mut result,
        )
    };
    VerifoneError::from_result(rc)?;
    Ok(result)
}

/// Safe wrapper around `vx_close_terminal`.
pub fn close_terminal(ptr: *mut VxTerminal) -> Result<(), VerifoneError> {
    let rc = unsafe { vx_close_terminal(ptr) };
    VerifoneError::from_result(rc)
}

#[cfg(test)]
mod stubs {
    use super::*;
    use std::ffi::{c_char, c_int, CStr};

    static mut NEXT_RESULT: i32 = 0;
    static mut HANDLE_ALLOCATED: bool = false;

    pub unsafe fn set_next_result(rc: i32) {
        NEXT_RESULT = rc;
    }

    #[no_mangle]
    pub extern "C" fn vx_init_terminal(out_terminal: *mut *mut VxTerminal) -> c_int {
        unsafe {
            if NEXT_RESULT != 0 {
                return NEXT_RESULT;
            }
            HANDLE_ALLOCATED = true;
            *out_terminal = 1usize as *mut VxTerminal;
            0
        }
    }

    #[no_mangle]
    pub extern "C" fn vx_start_transaction(
        _terminal: *mut VxTerminal,
        _amount_cents: u64,
        _currency: *const c_char,
    ) -> c_int {
        unsafe { NEXT_RESULT }
    }

    #[no_mangle]
    pub extern "C" fn vx_wait_for_card(
        _terminal: *mut VxTerminal,
        _timeout_ms: u32,
        out_card: *mut VxCardInfo,
    ) -> c_int {
        unsafe {
            if NEXT_RESULT != 0 {
                return NEXT_RESULT;
            }
            (*out_card).present = 1;
            let brand = CStr::from_bytes_with_nul(b"Visa\0").unwrap();
            let src = brand.as_ptr() as *const c_char;
            std::ptr::copy_nonoverlapping(src, (*out_card).brand.as_mut_ptr(), 5);
            let last4 = CStr::from_bytes_with_nul(b"4242\0").unwrap();
            let src = last4.as_ptr() as *const c_char;
            std::ptr::copy_nonoverlapping(src, (*out_card).last_four.as_mut_ptr(), 5);
            0
        }
    }

    #[no_mangle]
    pub extern "C" fn vx_process_payment(
        _terminal: *mut VxTerminal,
        out_result: *mut VxPaymentResult,
    ) -> c_int {
        unsafe {
            if NEXT_RESULT != 0 {
                return NEXT_RESULT;
            }
            let auth = CStr::from_bytes_with_nul(b"A1B2C3\0").unwrap();
            std::ptr::copy_nonoverlapping(
                auth.as_ptr() as *const c_char,
                (*out_result).auth_code.as_mut_ptr(),
                7,
            );
            let token = CStr::from_bytes_with_nul(b"opaque-token-123\0").unwrap();
            std::ptr::copy_nonoverlapping(
                token.as_ptr() as *const c_char,
                (*out_result).opaque_token.as_mut_ptr(),
                17,
            );
            let terminal = CStr::from_bytes_with_nul(b"verifone-42\0").unwrap();
            std::ptr::copy_nonoverlapping(
                terminal.as_ptr() as *const c_char,
                (*out_result).terminal_id.as_mut_ptr(),
                12,
            );
            (*out_result).authorized_amount_cents = 1234;
            0
        }
    }

    #[no_mangle]
    pub extern "C" fn vx_refund(
        _terminal: *mut VxTerminal,
        _transaction_id: *const c_char,
        _amount_cents: u64,
        _currency: *const c_char,
        out_result: *mut VxRefundResult,
    ) -> c_int {
        unsafe {
            if NEXT_RESULT != 0 {
                return NEXT_RESULT;
            }
            let reference = CStr::from_bytes_with_nul(b"refund-ref-001\0").unwrap();
            std::ptr::copy_nonoverlapping(
                reference.as_ptr() as *const c_char,
                (*out_result).reference.as_mut_ptr(),
                15,
            );
            (*out_result).refunded_amount_cents = 1234;
            0
        }
    }

    #[no_mangle]
    pub extern "C" fn vx_close_terminal(_terminal: *mut VxTerminal) -> c_int {
        unsafe {
            if HANDLE_ALLOCATED {
                HANDLE_ALLOCATED = false;
            }
            0
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::stubs::set_next_result;

    #[test]
    fn ffi_init_terminal_success() {
        unsafe { set_next_result(0) };
        let ptr = init_terminal().expect("init should succeed");
        assert!(!ptr.is_null());
        let _ = close_terminal(ptr);
    }

    #[test]
    fn ffi_init_terminal_failure() {
        unsafe { set_next_result(5) };
        assert!(init_terminal().is_err());
        unsafe { set_next_result(0) };
    }
}
