// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.5
// source: verifone/v1/verifone.proto

package verifonepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerifoneFFI_Authorize_FullMethodName = "/astra.verifone.v1.VerifoneFFI/Authorize"
	VerifoneFFI_Capture_FullMethodName   = "/astra.verifone.v1.VerifoneFFI/Capture"
	VerifoneFFI_Settle_FullMethodName    = "/astra.verifone.v1.VerifoneFFI/Settle"
)

// VerifoneFFIClient is the client API for VerifoneFFI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VerifoneFFI is the gRPC surface exposed by the Rust syncd verifone-ffi sidecar.
type VerifoneFFIClient interface {
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error)
}

type verifoneFFIClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifoneFFIClient(cc grpc.ClientConnInterface) VerifoneFFIClient {
	return &verifoneFFIClient{cc}
}

func (c *verifoneFFIClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResponse)
	err := c.cc.Invoke(ctx, VerifoneFFI_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifoneFFIClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, VerifoneFFI_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifoneFFIClient) Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleResponse)
	err := c.cc.Invoke(ctx, VerifoneFFI_Settle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifoneFFIServer is the server API for VerifoneFFI service.
// All implementations must embed UnimplementedVerifoneFFIServer
// for forward compatibility.
//
// VerifoneFFI is the gRPC surface exposed by the Rust syncd verifone-ffi sidecar.
type VerifoneFFIServer interface {
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
	Capture(context.Context, *CaptureRequest) (*CaptureResponse, error)
	Settle(context.Context, *SettleRequest) (*SettleResponse, error)
	mustEmbedUnimplementedVerifoneFFIServer()
}

// UnimplementedVerifoneFFIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifoneFFIServer struct{}

func (UnimplementedVerifoneFFIServer) Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedVerifoneFFIServer) Capture(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedVerifoneFFIServer) Settle(context.Context, *SettleRequest) (*SettleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Settle not implemented")
}
func (UnimplementedVerifoneFFIServer) mustEmbedUnimplementedVerifoneFFIServer() {}
func (UnimplementedVerifoneFFIServer) testEmbeddedByValue()                     {}

// UnsafeVerifoneFFIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifoneFFIServer will
// result in compilation errors.
type UnsafeVerifoneFFIServer interface {
	mustEmbedUnimplementedVerifoneFFIServer()
}

func RegisterVerifoneFFIServer(s grpc.ServiceRegistrar, srv VerifoneFFIServer) {
	// If the following call panics, it indicates UnimplementedVerifoneFFIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerifoneFFI_ServiceDesc, srv)
}

func _VerifoneFFI_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifoneFFIServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifoneFFI_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifoneFFIServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifoneFFI_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifoneFFIServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifoneFFI_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifoneFFIServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifoneFFI_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifoneFFIServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerifoneFFI_Settle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifoneFFIServer).Settle(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerifoneFFI_ServiceDesc is the grpc.ServiceDesc for VerifoneFFI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerifoneFFI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astra.verifone.v1.VerifoneFFI",
	HandlerType: (*VerifoneFFIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _VerifoneFFI_Authorize_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _VerifoneFFI_Capture_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _VerifoneFFI_Settle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verifone/v1/verifone.proto",
}
