// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: verifone/v1/verifone.proto

package verifonepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	KioskId       string                 `protobuf:"bytes,3,opt,name=kiosk_id,json=kioskId,proto3" json:"kiosk_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *AuthorizeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AuthorizeRequest) GetKioskId() string {
	if x != nil {
		return x.KioskId
	}
	return ""
}

func (x *AuthorizeRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *AuthorizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthorizeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // APPROVED, DECLINED, ERROR
	VerifoneToken string                 `protobuf:"bytes,2,opt,name=verifone_token,json=verifoneToken,proto3" json:"verifone_token,omitempty"`
	AuthCode      string                 `protobuf:"bytes,3,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	DeclineReason string                 `protobuf:"bytes,4,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	CardBrand     string                 `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardLastFour  string                 `protobuf:"bytes,6,opt,name=card_last_four,json=cardLastFour,proto3" json:"card_last_four,omitempty"`
	ReceiptText   string                 `protobuf:"bytes,7,opt,name=receipt_text,json=receiptText,proto3" json:"receipt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthorizeResponse) GetVerifoneToken() string {
	if x != nil {
		return x.VerifoneToken
	}
	return ""
}

func (x *AuthorizeResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *AuthorizeResponse) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

func (x *AuthorizeResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *AuthorizeResponse) GetCardLastFour() string {
	if x != nil {
		return x.CardLastFour
	}
	return ""
}

func (x *AuthorizeResponse) GetReceiptText() string {
	if x != nil {
		return x.ReceiptText
	}
	return ""
}

type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	VerifoneToken string                 `protobuf:"bytes,2,opt,name=verifone_token,json=verifoneToken,proto3" json:"verifone_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CaptureRequest) GetVerifoneToken() string {
	if x != nil {
		return x.VerifoneToken
	}
	return ""
}

type CaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DeclineReason string                 `protobuf:"bytes,2,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureResponse) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	VerifoneToken string                 `protobuf:"bytes,2,opt,name=verifone_token,json=verifoneToken,proto3" json:"verifone_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{4}
}

func (x *SettleRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *SettleRequest) GetVerifoneToken() string {
	if x != nil {
		return x.VerifoneToken
	}
	return ""
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DeclineReason string                 `protobuf:"bytes,2,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_verifone_v1_verifone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_verifone_v1_verifone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_verifone_v1_verifone_proto_rawDescGZIP(), []int{5}
}

func (x *SettleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettleResponse) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

var File_verifone_v1_verifone_proto protoreflect.FileDescriptor

const file_verifone_v1_verifone_proto_rawDesc = "" +
	"\n" +
	"\x1averifone/v1/verifone.proto\x12\x11astra.verifone.v1\"\xbe\x01\n" +
	"\x10AuthorizeRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x19\n" +
	"\bkiosk_id\x18\x03 \x01(\tR\akioskId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\"\xfe\x01\n" +
	"\x11AuthorizeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0everifone_token\x18\x02 \x01(\tR\rverifoneToken\x12\x1b\n" +
	"\tauth_code\x18\x03 \x01(\tR\bauthCode\x12%\n" +
	"\x0edecline_reason\x18\x04 \x01(\tR\rdeclineReason\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x05 \x01(\tR\tcardBrand\x12$\n" +
	"\x0ecard_last_four\x18\x06 \x01(\tR\fcardLastFour\x12!\n" +
	"\freceipt_text\x18\a \x01(\tR\vreceiptText\"V\n" +
	"\x0eCaptureRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12%\n" +
	"\x0everifone_token\x18\x02 \x01(\tR\rverifoneToken\"P\n" +
	"\x0fCaptureResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0edecline_reason\x18\x02 \x01(\tR\rdeclineReason\"U\n" +
	"\rSettleRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12%\n" +
	"\x0everifone_token\x18\x02 \x01(\tR\rverifoneToken\"O\n" +
	"\x0eSettleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0edecline_reason\x18\x02 \x01(\tR\rdeclineReason2\x86\x02\n" +
	"\vVerifoneFFI\x12V\n" +
	"\tAuthorize\x12#.astra.verifone.v1.AuthorizeRequest\x1a$.astra.verifone.v1.AuthorizeResponse\x12P\n" +
	"\aCapture\x12!.astra.verifone.v1.CaptureRequest\x1a\".astra.verifone.v1.CaptureResponse\x12M\n" +
	"\x06Settle\x12 .astra.verifone.v1.SettleRequest\x1a!.astra.verifone.v1.SettleResponseBlZjgithub.com/astra-systems/astra-service/services/payment-orchestrator/internal/client/verifonepb;verifonepbb\x06proto3"

var (
	file_verifone_v1_verifone_proto_rawDescOnce sync.Once
	file_verifone_v1_verifone_proto_rawDescData []byte
)

func file_verifone_v1_verifone_proto_rawDescGZIP() []byte {
	file_verifone_v1_verifone_proto_rawDescOnce.Do(func() {
		file_verifone_v1_verifone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_verifone_v1_verifone_proto_rawDesc), len(file_verifone_v1_verifone_proto_rawDesc)))
	})
	return file_verifone_v1_verifone_proto_rawDescData
}

var file_verifone_v1_verifone_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_verifone_v1_verifone_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),  // 0: astra.verifone.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil), // 1: astra.verifone.v1.AuthorizeResponse
	(*CaptureRequest)(nil),    // 2: astra.verifone.v1.CaptureRequest
	(*CaptureResponse)(nil),   // 3: astra.verifone.v1.CaptureResponse
	(*SettleRequest)(nil),     // 4: astra.verifone.v1.SettleRequest
	(*SettleResponse)(nil),    // 5: astra.verifone.v1.SettleResponse
}
var file_verifone_v1_verifone_proto_depIdxs = []int32{
	0, // 0: astra.verifone.v1.VerifoneFFI.Authorize:input_type -> astra.verifone.v1.AuthorizeRequest
	2, // 1: astra.verifone.v1.VerifoneFFI.Capture:input_type -> astra.verifone.v1.CaptureRequest
	4, // 2: astra.verifone.v1.VerifoneFFI.Settle:input_type -> astra.verifone.v1.SettleRequest
	1, // 3: astra.verifone.v1.VerifoneFFI.Authorize:output_type -> astra.verifone.v1.AuthorizeResponse
	3, // 4: astra.verifone.v1.VerifoneFFI.Capture:output_type -> astra.verifone.v1.CaptureResponse
	5, // 5: astra.verifone.v1.VerifoneFFI.Settle:output_type -> astra.verifone.v1.SettleResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_verifone_v1_verifone_proto_init() }
func file_verifone_v1_verifone_proto_init() {
	if File_verifone_v1_verifone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_verifone_v1_verifone_proto_rawDesc), len(file_verifone_v1_verifone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_verifone_v1_verifone_proto_goTypes,
		DependencyIndexes: file_verifone_v1_verifone_proto_depIdxs,
		MessageInfos:      file_verifone_v1_verifone_proto_msgTypes,
	}.Build()
	File_verifone_v1_verifone_proto = out.File
	file_verifone_v1_verifone_proto_goTypes = nil
	file_verifone_v1_verifone_proto_depIdxs = nil
}
