apiVersion: v1
kind: ConfigMap
metadata:
  name: astra-config
  namespace: astra-service
data:
  ASTRA_ENV: "production"
  ASTRA_NATS_URL: "nats://nats:4222"
  ASTRA_REDIS_URL: "redis://redis:6379/0"
  ASTRA_OTEL_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
  ASTRA_LOG_LEVEL: "info"
  GATEWAY_PORT: "8080"
  MENU_PORT: "8085"
  CART_PORT: "8081"
  ORDER_PORT: "8083"
  INVENTORY_PORT: "8082"
  PAYMENT_PORT: "8086"
  SYNC_PORT: "8087"
