# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lane_pb2 as lane__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LaneIntelServiceStub:
    """LaneIntelService exposes queue intelligence used to switch kiosk UI modes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQueueDepth = channel.unary_unary(
                '/astra.lane.v1.LaneIntelService/GetQueueDepth',
                request_serializer=lane__pb2.QueueDepthRequest.SerializeToString,
                response_deserializer=lane__pb2.QueueDepthResponse.FromString,
                _registered_method=True)
        self.StreamQueueDepth = channel.unary_stream(
                '/astra.lane.v1.LaneIntelService/StreamQueueDepth',
                request_serializer=lane__pb2.QueueDepthRequest.SerializeToString,
                response_deserializer=lane__pb2.QueueDepthResponse.FromString,
                _registered_method=True)


class LaneIntelServiceServicer:
    """LaneIntelService exposes queue intelligence used to switch kiosk UI modes.
    """

    def GetQueueDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQueueDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LaneIntelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQueueDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueDepth,
                    request_deserializer=lane__pb2.QueueDepthRequest.FromString,
                    response_serializer=lane__pb2.QueueDepthResponse.SerializeToString,
            ),
            'StreamQueueDepth': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamQueueDepth,
                    request_deserializer=lane__pb2.QueueDepthRequest.FromString,
                    response_serializer=lane__pb2.QueueDepthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astra.lane.v1.LaneIntelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astra.lane.v1.LaneIntelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LaneIntelService:
    """LaneIntelService exposes queue intelligence used to switch kiosk UI modes.
    """

    @staticmethod
    def GetQueueDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.lane.v1.LaneIntelService/GetQueueDepth',
            lane__pb2.QueueDepthRequest.SerializeToString,
            lane__pb2.QueueDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQueueDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.lane.v1.LaneIntelService/StreamQueueDepth',
            lane__pb2.QueueDepthRequest.SerializeToString,
            lane__pb2.QueueDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
