# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lane.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'lane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlane.proto\x12\rastra.lane.v1\x1a\x0c\x63ommon.proto\"I\n\x11QueueDepthRequest\x12\x18\n\x07lane_id\x18\x01 \x01(\tR\x07lane_id\x12\x1a\n\x08store_id\x18\x02 \x01(\tR\x08store_id\"\xc6\x01\n\x12QueueDepthResponse\x12\x18\n\x07lane_id\x18\x01 \x01(\tR\x07lane_id\x12\x1a\n\x08store_id\x18\x02 \x01(\tR\x08store_id\x12 \n\x0bqueue_depth\x18\x03 \x01(\x05R\x0bqueue_depth\x12\x36\n\x16\x65stimated_wait_seconds\x18\x04 \x01(\x05R\x16\x65stimated_wait_seconds\x12 \n\x0b\x63\x61ptured_at\x18\x05 \x01(\tR\x0b\x63\x61ptured_at2\xc3\x01\n\x10LaneIntelService\x12T\n\rGetQueueDepth\x12 .astra.lane.v1.QueueDepthRequest\x1a!.astra.lane.v1.QueueDepthResponse\x12Y\n\x10StreamQueueDepth\x12 .astra.lane.v1.QueueDepthRequest\x1a!.astra.lane.v1.QueueDepthResponse0\x01\x42?Z=github.com/astra-systems/astra-service/proto/gen/go/lane;laneb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/astra-systems/astra-service/proto/gen/go/lane;lane'
  _globals['_QUEUEDEPTHREQUEST']._serialized_start=43
  _globals['_QUEUEDEPTHREQUEST']._serialized_end=116
  _globals['_QUEUEDEPTHRESPONSE']._serialized_start=119
  _globals['_QUEUEDEPTHRESPONSE']._serialized_end=317
  _globals['_LANEINTELSERVICE']._serialized_start=320
  _globals['_LANEINTELSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
