package setup

import (
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const AppName = "Astra-System"

func Install(installDir, dataDir, channel string, silent bool) error {
	if err := ensureDirectory(installDir); err != nil {
		return fmt.Errorf("create install dir: %w", err)
	}
	if err := ensureDirectory(dataDir); err != nil {
		return fmt.Errorf("create data dir: %w", err)
	}
	if err := ensureDirectory(filepath.Join(dataDir, "config")); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	if err := ensureDirectory(filepath.Join(dataDir, "logs")); err != nil {
		return fmt.Errorf("create logs dir: %w", err)
	}
	if err := ensureDirectory(filepath.Join(dataDir, "compose")); err != nil {
		return fmt.Errorf("create compose dir: %w", err)
	}

	if err := writeConfig(dataDir, channel); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	if !silent {
		fmt.Println("  ✓ Directories created")
		fmt.Println("  ✓ Configuration written")
	}

	if err := installUpdater(installDir, dataDir); err != nil {
		return fmt.Errorf("install update agent: %w", err)
	}

	return nil
}

func ensureDirectory(path string) error {
	return os.MkdirAll(path, 0755)
}

func writeConfig(dataDir, channel string) error {
	cfg := fmt.Sprintf(`# Astra-System Runtime Configuration
# Auto-generated by installer — do not edit manually.

ASTRA_INSTALL_DIR=%s
ASTRA_DATA_DIR=%s
ASTRA_UPDATE_CHANNEL=%s
ASTRA_COMPOSE_DIR=%s
`, filepath.Join(dataDir, "..", AppName),
		dataDir,
		channel,
		filepath.Join(dataDir, "compose"))

	cfgPath := filepath.Join(dataDir, "config", "astra.conf")
	return os.WriteFile(cfgPath, []byte(cfg), 0644)
}

func installUpdater(installDir, dataDir string) error {
	updaterSrc := filepath.Join(installDir, "bin", "astra-updater.exe")
	if _, err := os.Stat(updaterSrc); os.IsNotExist(err) {
		return nil
	}

	cmd := exec.Command(updaterSrc, "install",
		"--data-dir", dataDir,
		"--install-dir", installDir,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		if strings.Contains(err.Error(), "already exists") {
			fmt.Println("  ✓ Update agent service already registered")
			return nil
		}
		return fmt.Errorf("register service: %w", err)
	}

	startCmd := exec.Command("sc", "start", "AstraUpdateAgent")
	_ = startCmd.Run()

	return nil
}
